import Footer from '@/components/Footer/Footer';
import Navigation from '@/components/Navigation/Navigation';
import '@/styles/main.scss';
import type { Metadata } from 'next';
import { NextIntlClientProvider } from 'next-intl';
import { Inter, Poppins } from 'next/font/google';
import SuccessModal from './orders/new/(components)/SuccessModal/SuccessModal';

export const inter = Inter({
  subsets: ['latin'],
  variable: '--font-inter',
});

export const poppins = Poppins({
  subsets: ['latin'],
  weight: ['100', '200', '400', '600', '700'],
  variable: '--font-poppins',
});

export const metadata: Metadata = {
  title: 'Maciej Solutions',
  description: 'Generated by create next app',
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal?: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${inter.variable} ${poppins.variable}`}>
      <body>
        <NextIntlClientProvider>
          <Navigation />
          {children}
          <Footer />
          {modal}
          <SuccessModal />
        </NextIntlClientProvider>
      </body>
    </html>
  );
}
